### ISSUE TITLE
[Debian] spl-dkms 0.6.5.2 fails to build against linux-rt 4.1.10 (vanilla kernel patched with the PREEMPT_RT and compiled locally)

### ISSUE THREAD

**Issue by Amitie10g** [zfsonlinux/spl#486]
So, I tried to build spl-dkms against the Vanilla Kernel 4.1.10 patched with the PREEMPT_RT, but building has failed. The following is the output of ``/var/lib/dkms/spl/0.6.5.2/build/make.log`` (some description of the errors are in spanish):
```
DKMS make.log for spl-0.6.5.2 for kernel 4.1.10-rt10-custom (x86_64)
mar oct 20 14:48:13 CLT 2015
make  all-recursive
make[1]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build'
Making all in module
make[2]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/module'
make -C /lib/modules/4.1.10-rt10-custom/build SUBDIRS=`pwd`  O=/lib/modules/4.1.10-rt10-custom/build CONFIG_SPL=m modules
make[3]: Entering directory '/home/davod/Descargas/kernel/linux-4.1.10-rt'
make[4]: Entering directory '/home/davod/Descargas/kernel/linux-4.1.10-rt'
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.o
In file included from /home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/spinlock.h:300:0,
                 from /home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/seqlock.h:35,
                 from /home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/time.h:5,
                 from /home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/stat.h:18,
                 from /home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/module.h:10,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/sysmacros.h:28,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/types.h:29,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:28,
                 from /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:27:
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h: En la función ‘spl_rw_set_owner’:
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:55:41: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_lock’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
                                         ^
/home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/spinlock_rt.h:42:16: nota: in definition of macro ‘spin_lock’
   rt_spin_lock(lock);  \
                ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:35:46: nota: in expansion of macro ‘spin_lock_irqsave’
 #define spl_rwsem_lock_irqsave(lk, fl)       spin_lock_irqsave(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:55:9: nota: in expansion of macro ‘spl_rwsem_lock_irqsave’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:57:46: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_lock’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
                                              ^
/home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/spinlock_rt.h:122:18: nota: in definition of macro ‘spin_unlock’
   rt_spin_unlock(lock);   \
                  ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:36:46: nota: in expansion of macro ‘spin_unlock_irqrestore’
 #define spl_rwsem_unlock_irqrestore(lk, fl)  spin_unlock_irqrestore(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:57:9: nota: in expansion of macro ‘spl_rwsem_unlock_irqrestore’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h: En la función ‘spl_rw_clear_owner’:
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:65:41: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_lock’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
                                         ^
/home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/spinlock_rt.h:42:16: nota: in definition of macro ‘spin_lock’
   rt_spin_lock(lock);  \
                ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:35:46: nota: in expansion of macro ‘spin_lock_irqsave’
 #define spl_rwsem_lock_irqsave(lk, fl)       spin_lock_irqsave(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:65:9: nota: in expansion of macro ‘spl_rwsem_lock_irqsave’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:67:46: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_lock’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
                                              ^
/home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/spinlock_rt.h:122:18: nota: in definition of macro ‘spin_unlock’
   rt_spin_unlock(lock);   \
                  ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:36:46: nota: in expansion of macro ‘spin_unlock_irqrestore’
 #define spl_rwsem_unlock_irqrestore(lk, fl)  spin_unlock_irqrestore(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:67:9: nota: in expansion of macro ‘spl_rwsem_unlock_irqrestore’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h: En la función ‘rw_owner’:
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:76:41: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_lock’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
                                         ^
/home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/spinlock_rt.h:42:16: nota: in definition of macro ‘spin_lock’
   rt_spin_lock(lock);  \
                ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:35:46: nota: in expansion of macro ‘spin_lock_irqsave’
 #define spl_rwsem_lock_irqsave(lk, fl)       spin_lock_irqsave(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:76:9: nota: in expansion of macro ‘spl_rwsem_lock_irqsave’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:78:46: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_lock’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
                                              ^
/home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/spinlock_rt.h:122:18: nota: in definition of macro ‘spin_unlock’
   rt_spin_unlock(lock);   \
                  ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:36:46: nota: in expansion of macro ‘spin_unlock_irqrestore’
 #define spl_rwsem_unlock_irqrestore(lk, fl)  spin_unlock_irqrestore(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:78:9: nota: in expansion of macro ‘spl_rwsem_unlock_irqrestore’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c: En la función ‘__rwsem_wake_one_writer_locked’:
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:56:12: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘activity’
         sem->activity = -1;
            ^
In file included from /home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/list.h:8:0,
                 from /home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/module.h:9,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/sysmacros.h:28,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/types.h:29,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:28,
                 from /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:27:
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:58:32: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_list’
         waiter = list_entry(sem->wait_list.next, struct rwsem_waiter, list);
                                ^
/home/davod/Descargas/kernel/linux-4.1.10-rt/include/linux/kernel.h:818:49: nota: in definition of macro ‘container_of’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                 ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:58:18: nota: in expansion of macro ‘list_entry’
         waiter = list_entry(sem->wait_list.next, struct rwsem_waiter, list);
                  ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c: En la función ‘__up_read_locked’:
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:73:18: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘activity’
         if (--sem->activity == 0 && !list_empty(&sem->wait_list))
                  ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:73:53: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_list’
         if (--sem->activity == 0 && !list_empty(&sem->wait_list))
                                                     ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c: En la función ‘__down_write_trylock_locked’:
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:84:16: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘activity’
         if (sem->activity == 0 && list_empty(&sem->wait_list)) {
                ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:84:50: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘wait_list’
         if (sem->activity == 0 && list_empty(&sem->wait_list)) {
                                                  ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:85:20: error: ‘struct rw_semaphore’ no tiene un miembro llamado ‘activity’
                 sem->activity = -1;
                    ^
/home/davod/Descargas/kernel/linux-4.1.10-rt/scripts/Makefile.build:258: recipe for target '/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.o' failed
make[6]: *** [/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.o] Error 1
/home/davod/Descargas/kernel/linux-4.1.10-rt/scripts/Makefile.build:403: recipe for target '/var/lib/dkms/spl/0.6.5.2/build/module/spl' failed
make[5]: *** [/var/lib/dkms/spl/0.6.5.2/build/module/spl] Error 2
/home/davod/Descargas/kernel/linux-4.1.10-rt/Makefile:1384: recipe for target '_module_/var/lib/dkms/spl/0.6.5.2/build/module' failed
make[4]: *** [_module_/var/lib/dkms/spl/0.6.5.2/build/module] Error 2
make[4]: Leaving directory '/home/davod/Descargas/kernel/linux-4.1.10-rt'
Makefile:146: recipe for target 'sub-make' failed
make[3]: *** [sub-make] Error 2
make[3]: Leaving directory '/home/davod/Descargas/kernel/linux-4.1.10-rt'
Makefile:11: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/module'
Makefile:586: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build'
Makefile:467: recipe for target 'all' failed
make: *** [all] Error 2
```
The configuration used is here https://gist.github.com/Amitie10g/2d673802d1bdc3ef0840

I built spl (and then zfs) successfully against the same kernel tree without the patch, with the same configuration (RT-related ones removed, obviously), so the problem is clearly the RT patch.

I know that previous Issues reported the same problem building problem, and as the 2015 ends, I want to know what is the status of spl and RT.

**Comment by kernelOfTruth** [comment]
related: https://github.com/zfsonlinux/zfs/issues/1510 Module build fails RT kernels - PlanetCCRMA - Ubuntu linux-low-latency

**Comment by Georgiy-Tugai** [comment]
Confirmed on Manjaro (Arch Linux derivative) x86_64 (building modules for `3.18.25-rt23-1-rt-lts` on `4.1.15-2-MANJARO`)
```
DKMS make.log for spl-0.6.5.2 for kernel 3.18.25-rt23-1-rt-lts (x86_64)
Mon Feb  1 16:37:08 ACDT 2016
make  all-recursive
make[1]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build'
Making all in include
make[2]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include'
Making all in fs
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/fs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/fs'
Making all in linux
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/linux'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/linux'
Making all in rpc
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/rpc'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/rpc'
Making all in sharefs
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/sharefs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/sharefs'
Making all in sys
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys'
Making all in fm
make[4]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys/fm'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys/fm'
Making all in fs
make[4]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys/fs'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys/fs'
Making all in sysevent
make[4]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys/sysevent'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys/sysevent'
make[4]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys'
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/sys'
Making all in util
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/util'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/util'
Making all in vm
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include/vm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include/vm'
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/include'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include'
make[2]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/include'
Making all in rpm
make[2]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/rpm'
Making all in generic
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/rpm/generic'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/rpm/generic'
Making all in redhat
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/rpm/redhat'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/rpm/redhat'
make[3]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/rpm'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/rpm'
make[2]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/rpm'
Making all in module
make[2]: Entering directory '/var/lib/dkms/spl/0.6.5.2/build/module'
make -C /usr/lib/modules/3.18.25-rt23-1-rt-lts/build SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory '/usr/lib/modules/3.18.25-rt23-1-rt-lts/build'
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.o
In file included from include/linux/spinlock.h:297:0,
                 from include/linux/seqlock.h:35,
                 from include/linux/time.h:5,
                 from include/linux/stat.h:18,
                 from include/linux/module.h:10,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/sysmacros.h:28,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/types.h:29,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:28,
                 from /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:27:
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h: In function ‘spl_rw_set_owner’:
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:55:41: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
                                         ^
include/linux/spinlock_rt.h:43:16: note: in definition of macro ‘spin_lock’
   rt_spin_lock(lock);  \
                ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:35:46: note: in expansion of macro ‘spin_lock_irqsave’
 #define spl_rwsem_lock_irqsave(lk, fl)       spin_lock_irqsave(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:55:9: note: in expansion of macro ‘spl_rwsem_lock_irqsave’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:57:46: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
                                              ^
include/linux/spinlock_rt.h:115:18: note: in definition of macro ‘spin_unlock’
   rt_spin_unlock(lock);   \
                  ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:36:46: note: in expansion of macro ‘spin_unlock_irqrestore’
 #define spl_rwsem_unlock_irqrestore(lk, fl)  spin_unlock_irqrestore(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:57:9: note: in expansion of macro ‘spl_rwsem_unlock_irqrestore’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h: In function ‘spl_rw_clear_owner’:
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:65:41: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
                                         ^
include/linux/spinlock_rt.h:43:16: note: in definition of macro ‘spin_lock’
   rt_spin_lock(lock);  \
                ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:35:46: note: in expansion of macro ‘spin_lock_irqsave’
 #define spl_rwsem_lock_irqsave(lk, fl)       spin_lock_irqsave(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:65:9: note: in expansion of macro ‘spl_rwsem_lock_irqsave’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:67:46: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
                                              ^
include/linux/spinlock_rt.h:115:18: note: in definition of macro ‘spin_unlock’
   rt_spin_unlock(lock);   \
                  ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:36:46: note: in expansion of macro ‘spin_unlock_irqrestore’
 #define spl_rwsem_unlock_irqrestore(lk, fl)  spin_unlock_irqrestore(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:67:9: note: in expansion of macro ‘spl_rwsem_unlock_irqrestore’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h: In function ‘rw_owner’:
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:76:41: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
                                         ^
include/linux/spinlock_rt.h:43:16: note: in definition of macro ‘spin_lock’
   rt_spin_lock(lock);  \
                ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:35:46: note: in expansion of macro ‘spin_lock_irqsave’
 #define spl_rwsem_lock_irqsave(lk, fl)       spin_lock_irqsave(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:76:9: note: in expansion of macro ‘spl_rwsem_lock_irqsave’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:78:46: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
                                              ^
include/linux/spinlock_rt.h:115:18: note: in definition of macro ‘spin_unlock’
   rt_spin_unlock(lock);   \
                  ^
/var/lib/dkms/spl/0.6.5.2/build/include/linux/rwsem_compat.h:36:46: note: in expansion of macro ‘spin_unlock_irqrestore’
 #define spl_rwsem_unlock_irqrestore(lk, fl)  spin_unlock_irqrestore(lk, fl)
                                              ^
/var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:78:9: note: in expansion of macro ‘spl_rwsem_unlock_irqrestore’
         spl_rwsem_unlock_irqrestore(&SEM(rwp)->wait_lock, flags);
         ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c: In function ‘__rwsem_wake_one_writer_locked’:
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:56:12: error: ‘struct rw_semaphore’ has no member named ‘activity’
         sem->activity = -1;
            ^
In file included from include/linux/list.h:8:0,
                 from include/linux/module.h:9,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/sysmacros.h:28,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/types.h:29,
                 from /var/lib/dkms/spl/0.6.5.2/build/include/sys/rwlock.h:28,
                 from /var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:27:
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:58:32: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
         waiter = list_entry(sem->wait_list.next, struct rwsem_waiter, list);
                                ^
include/linux/kernel.h:797:49: note: in definition of macro ‘container_of’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                 ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:58:18: note: in expansion of macro ‘list_entry’
         waiter = list_entry(sem->wait_list.next, struct rwsem_waiter, list);
                  ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c: In function ‘__up_read_locked’:
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:73:18: error: ‘struct rw_semaphore’ has no member named ‘activity’
         if (--sem->activity == 0 && !list_empty(&sem->wait_list))
                  ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:73:53: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
         if (--sem->activity == 0 && !list_empty(&sem->wait_list))
                                                     ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c: In function ‘__down_write_trylock_locked’:
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:84:16: error: ‘struct rw_semaphore’ has no member named ‘activity’
         if (sem->activity == 0 && list_empty(&sem->wait_list)) {
                ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:84:50: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
         if (sem->activity == 0 && list_empty(&sem->wait_list)) {
                                                  ^
/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.c:85:20: error: ‘struct rw_semaphore’ has no member named ‘activity’
                 sem->activity = -1;
                    ^
scripts/Makefile.build:257: recipe for target '/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.o' failed
make[5]: *** [/var/lib/dkms/spl/0.6.5.2/build/module/spl/spl-rwlock.o] Error 1
scripts/Makefile.build:402: recipe for target '/var/lib/dkms/spl/0.6.5.2/build/module/spl' failed
make[4]: *** [/var/lib/dkms/spl/0.6.5.2/build/module/spl] Error 2
Makefile:1381: recipe for target '_module_/var/lib/dkms/spl/0.6.5.2/build/module' failed
make[3]: *** [_module_/var/lib/dkms/spl/0.6.5.2/build/module] Error 2
make[3]: Leaving directory '/usr/lib/modules/3.18.25-rt23-1-rt-lts/build'
Makefile:11: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build/module'
Makefile:588: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/spl/0.6.5.2/build'
Makefile:469: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kernelOfTruth** [comment]
https://github.com/zfsonlinux/zfs/issues/1510#issuecomment-143354960 not sure if the low-latency ubuntu kernel is a real RT kernel (e.g. kernel 3.13-10 low latency)

but that worked and 4.4.1-rt4 also works.

So it's either an configuration issue or RT_FULL (still ?) doesn't work

I went with
```
CONFIG_PREEMPT=y
CONFIG_PREEMPT_RT_BASE=y
CONFIG_HAVE_PREEMPT_LAZY=y
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
# CONFIG_PREEMPT__LL is not set
CONFIG_PREEMPT_RTB=y
# CONFIG_PREEMPT_RT_FULL is not set
```

CONFIG_PREEMPT_RTB=y instead of CONFIG_PREEMPT_RT_FULL

perhaps that lets it succeed ?

Anyway I'm off to test & see how an rt-kernel behaves (never used one before)

**Comment by Georgiy-Tugai** [comment]
The relevant segment of my kernel config:
```
CONFIG_PREEMPT=y
CONFIG_PREEMPT_RT_BASE=y
CONFIG_HAVE_PREEMPT_LAZY=y
CONFIG_PREEMPT_LAZY=y
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
# CONFIG_PREEMPT__LL is not set
# CONFIG_PREEMPT_RTB is not set
CONFIG_PREEMPT_RT_FULL=y
```
I'll try with `CONFIG_PREEMPT_RT_FULL` unset and `CONFIG_PREEMPT_RTB` set.

**Comment by kernelOfTruth** [comment]
Alright, the issue appears to lie with full preemption

```CONFIG_PREEMPT_RTB``` works

```CONFIG_PREEMPT_RT_FULL``` leads to


```
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c: In function ‘__rwsem_wake_one_writer_locked’:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:56:12: error: ‘struct rw_semaphore’ has no member named ‘activity’
         sem->activity = -1;
            ^
In file included from include/linux/list.h:8:0,
                 from include/linux/module.h:9,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/sysmacros.h:28,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/types.h:29,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/rwlock.h:28,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:27:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:58:32: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
         waiter = list_entry(sem->wait_list.next, struct rwsem_waiter, list);
                                ^
include/linux/kernel.h:818:49: note: in definition of macro ‘container_of’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                 ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:58:18: note: in expansion of macro ‘list_entry’
         waiter = list_entry(sem->wait_list.next, struct rwsem_waiter, list);
                  ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c: In function ‘__up_read_locked’:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:73:18: error: ‘struct rw_semaphore’ has no member named ‘activity’
         if (--sem->activity == 0 && !list_empty(&sem->wait_list))
                  ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:73:53: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
         if (--sem->activity == 0 && !list_empty(&sem->wait_list))
                                                     ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c: In function ‘__down_write_trylock_locked’:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:84:16: error: ‘struct rw_semaphore’ has no member named ‘activity’
         if (sem->activity == 0 && list_empty(&sem->wait_list)) {
                ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:84:50: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
         if (sem->activity == 0 && list_empty(&sem->wait_list)) {
                                                  ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:85:20: error: ‘struct rw_semaphore’ has no member named ‘activity’
                 sem->activity = -1;
                    ^
scripts/Makefile.build:258: recipe for target '/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.o' failed
```

**Comment by kernelOfTruth** [comment]
referencing: 
https://github.com/zfsonlinux/spl/issues/218 Cannot compile on the latest Debian stable with rt-686-pae kernel
https://github.com/zfsonlinux/spl/issues/308 Unable to compile on 3.10-3-rt-amd64

**Comment by ryao** [comment]
We had to implement our own rw_tryupgrade because there is no Linux equivalent, but the -rt patchset replaced semaphores with mutexes, breaking that:

https://github.com/clrkwllms/rt-linux/blob/a493acd45b2e89a711b9f0557dbf04af78c4699c/include/linux/rwsem_rt.h
https://github.com/clrkwllms/rt-linux/commit/cb893e386fb17150638544cecb691b67c1819886

Making this work (assuming the changed semantics do not cause bugs) would be a simple matter of doing:

```
#define rw_tryupgrade(rwp)                                              \
({                                                                      \
        int _rc_ = 1;                                                   \
                                                                        \
        spl_rw_lockdep_off_maybe(rwp);                                  \
        if ((rt_mutex_owner(lock) == current) &&                                  \
            ((rwp)->read_depth == 0)) {                                \
                --(rwp)->read_depth;                       \
                _rc_ = 0;   \
        }                                                               \
        _rc_;                                                           \
})
```

**Comment by behlendorf** [comment]
You might just want to cherry pick a6ae97caed620b0e9e0575346062c751f6f15483 from master.  It should remove the offending code entirely and the updated semantics should be entirely safe.

**Comment by kernelOfTruth** [comment]
Just entirely missed this !

So this means RT_FULL is supposed to work now ?

Nice !

I'll take a look at it in the weekend and see if it works

Great sideeffect :+1:

**Comment by behlendorf** [comment]
@kernelOfTruth _maybe_, you'll have to tell me after you try it out.  :)

**Comment by behlendorf** [comment]
Closing this is believe to have been fixed in master and is awaiting verification.

**Comment by kernelOfTruth** [comment]
@behlendorf SPL still fails to compile when RT_FULL is enabled, no change:

```
In file included from include/linux/spinlock.h:290:0,
                 from include/linux/seqlock.h:35,
                 from include/linux/time.h:5,
                 from include/linux/stat.h:18,
                 from include/linux/module.h:10,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/sysmacros.h:28,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/types.h:29,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/rwlock.h:28,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:27:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c: In function ‘__rwsem_tryupgrade’:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:41:31: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
  spl_rwsem_lock_irqsave(&rwsem->wait_lock, flags);
                               ^
include/linux/spinlock_rt.h:44:40: note: in definition of macro ‘spin_lock’
 #define spin_lock(lock)   rt_spin_lock(lock)
                                        ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/linux/rwsem_compat.h:52:46: note: in expansion of macro ‘spin_lock_irqsave’
 #define spl_rwsem_lock_irqsave(lk, fl)       spin_lock_irqsave(lk, fl)
                                              ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:41:2: note: in expansion of macro ‘spl_rwsem_lock_irqsave’
  spl_rwsem_lock_irqsave(&rwsem->wait_lock, flags);
  ^
In file included from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/rwlock.h:30:0,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:27:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/linux/rwsem_compat.h:42:29: error: ‘struct rw_semaphore’ has no member named ‘count’
 #define RWSEM_COUNT(sem) sem->count
                             ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:42:6: note: in expansion of macro ‘RWSEM_COUNT’
  if (RWSEM_COUNT(rwsem) == SPL_RWSEM_SINGLE_READER_VALUE &&
      ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:43:23: error: ‘struct rw_semaphore’ has no member named ‘wait_list’
      list_empty(&rwsem->wait_list)) {
                       ^
In file included from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/rwlock.h:30:0,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:27:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/linux/rwsem_compat.h:42:29: error: ‘struct rw_semaphore’ has no member named ‘count’
 #define RWSEM_COUNT(sem) sem->count
                             ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:45:3: note: in expansion of macro ‘RWSEM_COUNT’
   RWSEM_COUNT(rwsem) = SPL_RWSEM_SINGLE_WRITER_VALUE;
   ^
In file included from include/linux/spinlock.h:290:0,
                 from include/linux/seqlock.h:35,
                 from include/linux/time.h:5,
                 from include/linux/stat.h:18,
                 from include/linux/module.h:10,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/sysmacros.h:28,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/types.h:29,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/sys/rwlock.h:28,
                 from /var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:27:
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:47:36: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
  spl_rwsem_unlock_irqrestore(&rwsem->wait_lock, flags);
                                    ^
include/linux/spinlock_rt.h:114:44: note: in definition of macro ‘spin_unlock’
 #define spin_unlock(lock)   rt_spin_unlock(lock)
                                            ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/include/linux/rwsem_compat.h:53:46: note: in expansion of macro ‘spin_unlock_irqrestore’
 #define spl_rwsem_unlock_irqrestore(lk, fl)  spin_unlock_irqrestore(lk, fl)
                                              ^
/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.c:47:2: note: in expansion of macro ‘spl_rwsem_unlock_irqrestore’
  spl_rwsem_unlock_irqrestore(&rwsem->wait_lock, flags);
  ^
scripts/Makefile.build:291: recipe for target '/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.o' failed
make[5]: *** [/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl/spl-rwlock.o] Error 1
make[5]: *** Waiting for unfinished jobs....
scripts/Makefile.build:440: recipe for target '/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl' failed
make[4]: *** [/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module/spl] Error 2
Makefile:1429: recipe for target '_module_/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module' failed
make[3]: *** [_module_/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module] Error 2
make[3]: Leaving directory '/usr/src/linux-4.6.1-rt3+for-linus-4.7'
Makefile:11: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999/module'
Makefile:588: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/sys-kernel/spl-9999-r1/work/spl-9999'
Makefile:469: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: sys-kernel/spl-9999-r1::portage failed (compile phase):
 *   emake failed
```
